---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  region: us-east-1
  instance_type: m3.medium

transport:
  connection_timeout: 10
  connection_retries: 5
  ssh_key: <%= ENV['AWS_PRIVATE_KEY'] %>

provisioner:
  name: chef_zero
  data_path: ci

platforms:
  - name: amazon
    driver:
      image_id: ami-60b6c60a
    transport:
      username: ec2-user
  - name: centos-6
    driver:
      image_id: ami-57cd8732
    transport:
      username: centos
  - name: centos-7
    driver:
      image_id: ami-61bbf104
    transport:
      username: centos
  - name: debian-8
    driver:
      image_id: ami-8b9a63e0
    transport:
      username: admin
  - name: ubuntu-12
    driver:
      image_id: ami-427a392a
    transport:
      username: ubuntu
  - name: ubuntu-14
    driver:
      image_id: ami-663a6e0c
    transport:
      username: ubuntu
  - name: rhel-6
    driver:
      image_id: ami-0d28fe66
    transport:
      username: ec2-user
  - name: rhel-7
    driver:
      image_id: ami-a8d369c0
    transport:
      username: ec2-user

suites:
  - name: default
    run_list:
      - recipe[conjur::client]
      - recipe[conjur::conjurrc]
      - recipe[conjur::install]
      - recipe[conjur::configure]
    attributes:
      conjur:
        identity:
          account: cucumber
          login: <%= ENV['CONJUR_AUTHN_LOGIN'] %>
          password: <%= ENV['CONJUR_AUTHN_API_KEY'] %>
        configuration:
          account: cucumber
          appliance_url: <%= ENV['CONJUR_APPLIANCE_URL'] %>
          ssl_certificate: "<%= ENV['CONJUR_SSL_CERTIFICATE'] %>"
