---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_path: ci

platforms:
  - name: ubuntu-14.04
  - name: debian-8.3

suites:
  - name: foundation
    run_list:
      - recipe[conjur::install]
      - recipe[conjur::conjurrc]
      - recipe[conjur::client]
    attributes:
      conjur:
        configuration:
          account: conjurops
          appliance_url: https://conjur-master.itp.conjur.net/api
          ssl_certificate: "<%= File.readlines('/Users/dustin/conjur-conjurops.pem').join('\n') %>"
