---
driver:
  name: ec2
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  region: us-east-1
  instance_type: m3.medium

transport:
  connection_timeout: 10
  connection_retries: 5
  ssh_key: <%= ENV['AWS_PRIVATE_KEY'] %>

driver_config:
  privileged: true
  socket: <%= ENV['DOCKER_HOST'] || 'unix:///var/run/docker.sock' %>

provisioner:
  name: chef_zero
  data_path: ci

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
    driver:
      image_id: ami-9eaa1cf6
    transport:
      username: ubuntu
  - name: amazon
    driver:
      image_id: ami-2051294a
    transport:
      username: ec2-user
  - name: debian-8
    driver:
      image_id: ami-8b9a63e0
    transport:
      username: admin
  - name: centos-6
    driver:
      image_id: ami-bc8131d4
    transport:
      username: root
  - name: centos-7
    driver:
      image_id: ami-61bbf104
    transport:
      username: centos

suites:
  - name: default
    run_list:
      - recipe[conjur::client]
      - recipe[conjur::conjurrc]
      - recipe[conjur::install]
      - recipe[conjur::configure]
    attributes:
      conjur:
        identity:
          account: cucumber
          login: <%= ENV['CONJUR_AUTHN_LOGIN'] %>
          password: <%= ENV['CONJUR_AUTHN_API_KEY'] %>
        configuration:
          account: cucumber
          appliance_url: <%= ENV['CONJUR_APPLIANCE_URL'] %>
          ssl_certificate: "<%= ENV['CONJUR_SSL_CERTIFICATE'] %>"
