---
driver_plugin: docker

driver_config:
  use_sudo: true
  privileged: true
  socket: <%= ENV['DOCKER_HOST'] || 'unix:///var/run/docker.sock' %>

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.5
  #- name: amazon-linux
  #  driver_config:
  #    image: vettl/amazon-linux:2014.03
  #- name: rhel6.5
  #  driver_config:
  #    image: richxsl/rhel6.5

suites:
  - name: default
    run_list:
      - recipe[conjur::client]
      - recipe[conjur::conjurrc]
      - recipe[conjur::install]
    attributes:
      conjur:
        configuration:
          account: demo
          appliance_url: https://conjur/api
          ssl_certificate: |
            -----BEGIN CERTIFICATE-----
            MIICzTCCAbWgAwIBAgIJAIMlw8P9K504MA0GCSqGSIb3DQEBBQUAMBExDzANBgNV
            BAMTBmNvbmp1cjAeFw0xNTAzMjUxNzQ3NTJaFw0yNTAzMjIxNzQ3NTJaMBExDzAN
            BgNVBAMTBmNvbmp1cjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBALHh
            pZbvPIEeG7cLIG0qEFoq8P6abnWZrA9C37D8aUwXMW+8q6tP6oWxI1bRF3Ym73Fp
            GNsB/eS548boXvyYkwSsmfTEZ6GY7I2Ey9spgVtt18s/1FoKrx+WMmbYBkHEos26
            KEVZuJ0pbVQxvtH9MmdRQZzZfmNMFLYWNW9jsg6pd3qEH8w6ba617vJf6m0baLRE
            r3GWLTWlzjTthZSzJBw94fnIBkCvYiNU3zmZy8qrFWQ+EYYV0do5XeOh5wPXAjUi
            HBnpvIFJkO/ex3YxS87QHr8yfbVPj6wzP1VRviroZarOvyDvzrXU2leWjRvmHo5m
            g8GwV+Ws+7hr5RwJkFcCAwEAAaMoMCYwJAYDVR0RBB0wG4IJbG9jYWxob3N0ggZj
            b25qdXKCBmNvbmp1cjANBgkqhkiG9w0BAQUFAAOCAQEApZAY6LDQnpDd798JN2a4
            N/PDZ306qn6K0YNSpIAfz8xMSazEoISG4At2wQy5yKyyfiS804+XpGHxMdC2N+F5
            AE558AsrfJB5OyRguxeKqTgOO6ZpYJ57x7G8OWqxCft0QizCXQszr6q2wRttkd3U
            qVeLCUZJfwK7mY0iS5bpZM4pKWIjH9Zdkh7mbrhnNtO+tiNQnf3YrX/U2+d89bwF
            8XV4phCuptb75KspvmhjB4EpzU5vZYnEKWUIzIQMztdbf/JMet2vG+C2xNCOTRnC
            rG+Mmg4IiA+YnPrnR2UiFLrK4HiWWOgV3fJnU0zi0lfCzpSD7WPO6NuvAfOVNd3m
            cA==
            -----END CERTIFICATE-----
