---
driver:
  name: ec2
  region: us-east-1
  subnet_id: subnet-d0a7edef
  aws_ssh_key_id: test-kitchen
  security_group_ids: [sg-a483a1d3]
  tags:
    created-by: test-kitchen
    Name: conjur cookbook test kitchen

transport:
  connection_timeout: 10
  connection_retries: 5
  ssh_key: /var/sshkey.pem

provisioner:
  name: chef_zero
  data_path: ci

# TODO these platforms need fixing
broken_platforms:
  - name: amazon
    driver:
      image_id: ami-0b33d91d  # Amazon Linux 2016.09.1, hvm:ebs-ssd
    transport:
      username: ec2-user
  - name: centos-6
    driver:
      image_id: ami-57cd8732
    transport:
      username: centos
  - name: centos-7
    driver:
      image_id: ami-61bbf104
    transport:
      username: centos
  - name: debian-8
    driver:
      image_id: ami-8b9a63e0
    transport:
      username: admin
  - name: ubuntu-12
    driver:
      image_id: ami-427a392a
    transport:
      username: ubuntu
  - name: ubuntu-14
    driver:
      image_id: ami-663a6e0c
    transport:
      username: ubuntu

platforms:
  - name: ubuntu-16
    driver:
      image_id: ami-2757f631  # Ubuntu 16.04LTS, hvm:ebs-ssd, 20170307
    transport:
      username: ubuntu
  - name: rhel-6
    driver:
      image_id: ami-0d28fe66
    transport:
      username: ec2-user
  - name: rhel-7
    driver:
      image_id: ami-a8d369c0
    transport:
      username: ec2-user

suites:
  - name: default
    run_list:
      - recipe[conjur::client]
      - recipe[conjur::conjurrc]
      - recipe[conjur::install]
      - recipe[conjur::configure]
    attributes:
      conjur:
        identity:
          account: cucumber
          login: host/test
          password: password
        configuration:
          account: cucumber
          appliance_url: https://appliance.test.com
          ssl_certificate: "dummysslcertcontent"
