Vagrant.configure(2) do |config|
  config.vm.box = 'phusion/ubuntu-14.04-amd64'

  config.vm.synced_folder ".", "/vagrant", :type => "rsync", :rsync__exclude => ['*~', './output/'], :rsync__verbose => true


  config.vm.provider :aws do |aws, override|
    override.vm.box_url="https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"

    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
        
    aws.ami = 'ami-b1174cdb' # ENV['AWS_BASE_AMI']
    aws.keypair_name = ENV['AWS_SSH_KEY_ID']
    aws.instance_type="m3.medium"
    aws.tags = { 'Name' => 'cookbook-conjur-ci' }
    override.ssh.private_key_path = ENV['AWS_PRIVATE_KEY']
    override.ssh.username = 'ubuntu'
    
  end
end
